//! [`Engine`] — the main entry point for running redaction pipelines.
//!
//! A pipeline run progresses through five phases:
//!
//! 1. **Config merge** — per-request [`RuntimeConfig`] overrides are merged
//!    with the engine's base config (section-level replacement).
//! 2. **Context acquisition** — [`LoadContext`](nvisy_ontology::workflow::LoadContext)
//!    nodes are scanned and their context IDs are acquired from the
//!    engine's [`ContextCache`](super::cache::ContextCache) (loaded from the
//!    registry on first access, deduplicated across concurrent runs).
//! 3. **Compile** — the [`Graph`] is compiled into an
//!    [`ExecutionPlan`](super::plan::ExecutionPlan) via [`plan::compile`].
//! 4. **Schedule & execute** — the [orchestrator](super::orchestrator)
//!    spawns one task per node and collects results.
//! 5. **Finalize** — entity and redaction counts are computed from node
//!    results, the run status is recorded, acquired contexts are released
//!    from the cache, and an [`EngineOutput`] is returned to the caller.
//!
//! All mutable state lives in [`EngineInner`] behind an `Arc`. Builder
//! methods (e.g. [`Engine::with_key_provider`]) require exclusive access
//! via `Arc::get_mut` and must be called before the engine is cloned.

use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;

use nvisy_core::Error;
use nvisy_core::content::{Content, ContentMetadata};
use nvisy_ontology::context::Context;
use nvisy_ontology::policy::{Policies, Retention, RetentionScope};
use nvisy_ontology::provenance::Audit;
use nvisy_ontology::workflow::{Graph, GraphNodeKind};
use nvisy_provider::http::HttpClient;
use schemars::JsonSchema;
use serde::Serialize;
use tokio_util::sync::CancellationToken;
use uuid::Uuid;
use validator::Validate;

use super::cache::ContextCache;
use super::config::RuntimeConfig;
use super::executor::RunOutput;
use super::orchestrator::{self, RunContext};
use super::plan;
use super::runs::state::{RunRecord, RunState};
use super::runs::{
    AnalyticsSnapshot, NodeSnapshot, NodeStatus, RunEntry, RunFilter, RunSnapshot, RunStatus,
};
use crate::operation::encryption::SharedKeyProvider;
use crate::operation::envelope::SharedData;
use crate::registry::Registry;

/// Input required to execute a redaction pipeline.
///
/// Bundles the actor identity, redaction policies, execution graph, and
/// optional per-request configuration overrides into a single submission.
pub struct EngineInput {
    /// Identity of the human or service account initiating the run.
    pub actor_id: Uuid,
    /// Redaction policies to apply (at least one required).
    pub policies: Policies,
    /// Execution graph defining the pipeline DAG.
    ///
    /// Content identifiers live on [`ImportFile`](nvisy_ontology::workflow::ImportFile)
    /// nodes within the graph, not as a top-level field.
    pub graph: Graph,
    /// Per-request configuration overrides, merged with engine defaults
    /// via [`RuntimeConfig::merge`] at the start of each run.
    pub config: Option<RuntimeConfig>,
    /// When `true`, the pipeline evaluates detection and policy rules
    /// but skips validation and export. The returned [`EngineOutput`]
    /// contains the redaction plan (decisions and records) without
    /// modifying or exporting any content.
    pub dry_run: bool,
}

/// Complete result of a pipeline run.
///
/// Contains a per-phase breakdown — detection results, policy evaluation
/// decisions, per-source redaction summaries, and audit records — along
/// with the run identifier for correlation.
#[derive(Debug, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct EngineOutput {
    /// Unique identifier for this run, generated by [`Engine::run`].
    pub run_id: Uuid,
    /// Per-document audit trails: entities, redaction entries, and
    /// content source metadata. One audit per processed document.
    pub audits: Vec<Audit>,
}

/// Shared inner state for the engine, held behind an `Arc`.
///
/// All fields are immutable after construction except [`RunState`],
/// which uses internal `RwLock` synchronization.
struct EngineInner {
    /// Base configuration, merged with per-request overrides at runtime.
    runtime_config: RuntimeConfig,
    /// Shared HTTP client for all downstream API calls.
    http_client: HttpClient,
    /// Content and context storage backend.
    registry: Registry,
    /// Encryption key provider for import/export decrypt/encrypt operations.
    key_provider: Option<SharedKeyProvider>,
    /// Ref-counted context cache shared across concurrent runs.
    context_cache: ContextCache,
    /// In-memory run lifecycle tracker (volatile — lost on restart).
    runs: RunState,
}

/// The redaction pipeline engine.
///
/// All state lives in `Arc<EngineInner>` and is shared across clones.
/// Builder methods (`with_config`, `with_retry`, etc.) use
/// `Arc::get_mut` and must be called before the engine is cloned.
#[derive(Clone)]
pub struct Engine {
    inner: Arc<EngineInner>,
}

impl std::fmt::Debug for Engine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Engine")
            .field("runtime_config", &self.inner.runtime_config)
            .field("http_client", &self.inner.http_client)
            .finish()
    }
}

impl Engine {
    /// Open a new engine with the given configuration and data directory.
    ///
    /// Constructs the HTTP client, registry, and run state from the
    /// provided config. Extracts default retry/timeout policies and
    /// run eviction limits from the `[engine]` section, if present.
    ///
    /// # Errors
    ///
    /// Returns an error if the registry database cannot be opened.
    pub fn open(data_dir: impl AsRef<Path>, config: RuntimeConfig) -> Result<Self, Error> {
        let registry = Registry::open(data_dir.as_ref())?;

        let http_config = config
            .engine
            .as_ref()
            .and_then(|e| e.http.clone())
            .unwrap_or_default();
        let http_client = HttpClient::new(&http_config)?;

        Ok(Self {
            inner: Arc::new(EngineInner {
                runtime_config: config,
                http_client,
                registry,
                key_provider: None,
                context_cache: ContextCache::new(),
                runs: RunState::new(),
            }),
        })
    }

    /// Create a temporary engine backed by a [`tempfile`] directory.
    ///
    /// Uses default configuration. The directory is deleted when the
    /// returned [`TempDir`](tempfile::TempDir) is dropped — keep it
    /// alive for the duration of the test.
    ///
    /// # Panics
    ///
    /// Panics if the temp directory or registry cannot be created.
    #[cfg(any(test, feature = "test-utils"))]
    pub fn temp() -> (Self, tempfile::TempDir) {
        let dir = tempfile::tempdir().expect("failed to create temp directory");
        let engine = Self::open(dir.path(), RuntimeConfig::default())
            .expect("failed to open engine in temp directory");
        (engine, dir)
    }

    /// Set the key provider for encryption/decryption operations.
    ///
    /// # Panics
    ///
    /// Panics if the engine has already been cloned (Arc is shared).
    pub fn with_key_provider(mut self, provider: SharedKeyProvider) -> Self {
        Arc::get_mut(&mut self.inner)
            .expect("engine must not be shared during construction")
            .key_provider = Some(provider);
        self
    }

    /// Returns the base runtime configuration before per-request overrides.
    pub fn config(&self) -> &RuntimeConfig {
        &self.inner.runtime_config
    }

    /// Returns the shared HTTP client.
    pub fn http_client(&self) -> &HttpClient {
        &self.inner.http_client
    }

    /// Returns the content and context registry.
    pub fn registry(&self) -> &Registry {
        &self.inner.registry
    }

    /// Execute a full redaction pipeline.
    ///
    /// Compiles the graph, pre-loads contexts, runs the DAG orchestrator,
    /// and collects results. See the module-level docs for the full
    /// phase breakdown.
    ///
    /// # Errors
    ///
    /// Returns an error if graph compilation fails, the run times out, or
    /// all nodes fail during execution.
    pub async fn run(&self, input: EngineInput) -> Result<EngineOutput, Error> {
        let run_id = uuid::Uuid::new_v4();
        let cancel = CancellationToken::new();

        let effective_config = match &input.config {
            Some(overrides) => self.inner.runtime_config.merge(overrides),
            None => self.inner.runtime_config.clone(),
        };

        let mut context_ids: Vec<Uuid> = input
            .graph
            .nodes
            .iter()
            .filter_map(|node| match &node.kind {
                GraphNodeKind::LoadContext(cfg) => Some(cfg.context_ids.clone()),
                _ => None,
            })
            .flatten()
            .collect();
        context_ids.sort_unstable();
        context_ids.dedup();

        let limits = effective_config
            .engine
            .as_ref()
            .map(|e| e.limits)
            .unwrap_or_default();
        let concurrency = input
            .graph
            .concurrency
            .or_else(|| effective_config.engine.as_ref().and_then(|e| e.concurrency));

        if let Some(ref c) = concurrency {
            c.validate()
                .map_err(|e| Error::validation(e.to_string(), "concurrency"))?;
        }

        let record = RunRecord {
            actor_id: input.actor_id,
            status: RunStatus::Failed,
            created_at: jiff::Timestamp::now(),
            started_at: None,
            completed_at: Some(jiff::Timestamp::now()),
            nodes: HashMap::new(),
            cancel: cancel.clone(),
            entities_detected: 0,
            redactions_applied: 0,
        };

        let compiled = match plan::compile(&input.graph, limits.channel_buffer) {
            Ok(plan) => plan,
            Err(e) => {
                self.inner.runs.insert(run_id, record).await;
                return Err(e);
            }
        };

        let initial_nodes: HashMap<Uuid, NodeSnapshot> = compiled
            .nodes()
            .iter()
            .map(|n| {
                (
                    n.node.id,
                    NodeSnapshot {
                        node_id: n.node.id,
                        status: NodeStatus::Pending,
                        items_processed: 0,
                        error: None,
                    },
                )
            })
            .collect();

        self.inner
            .runs
            .insert(
                run_id,
                RunRecord {
                    actor_id: input.actor_id,
                    status: RunStatus::Running,
                    created_at: jiff::Timestamp::now(),
                    started_at: None,
                    completed_at: None,
                    nodes: initial_nodes,
                    cancel: cancel.clone(),
                    entities_detected: 0,
                    redactions_applied: 0,
                },
            )
            .await;

        // Acquire contexts into the shared cache. The returned guard
        // releases them (decrementing ref counts) when dropped — even
        // if this function panics.
        let _context_guard = self
            .inner
            .context_cache
            .acquire(input.actor_id, &context_ids, &self.inner.registry)
            .await;

        let mut shared_data = SharedData {
            run_id,
            actor_id: input.actor_id,
            policies: input.policies.clone(),
            registry: self.inner.registry.clone(),
            key_provider: SharedKeyProvider::default(),
            context_cache: self.inner.context_cache.clone(),
        };
        if let Some(ref kp) = self.inner.key_provider {
            shared_data.key_provider = kp.clone();
        }

        let cancel_clone = cancel.clone();
        let ctx = RunContext {
            cancel,
            shared: Arc::new(shared_data),
            config: Arc::new(effective_config),
            http_client: self.inner.http_client.clone(),
            concurrency,
            dry_run: input.dry_run,
        };

        self.inner.runs.set_started_at(run_id).await;

        let run_output = if let Some(ms) = limits.run_timeout_ms {
            match tokio::time::timeout(
                std::time::Duration::from_millis(ms),
                orchestrator::run_graph(&compiled, run_id, self.inner.runs.clone(), ctx),
            )
            .await
            {
                Ok(Ok(output)) => output,
                Ok(Err(e)) => {
                    self.inner.runs.fail(run_id).await;
                    return Err(e);
                }
                Err(_) => {
                    cancel_clone.cancel();
                    self.inner.runs.fail(run_id).await;
                    return Err(Error::timeout("pipeline run exceeded time limit"));
                }
            }
        } else {
            match orchestrator::run_graph(&compiled, run_id, self.inner.runs.clone(), ctx).await {
                Ok(output) => output,
                Err(e) => {
                    self.inner.runs.fail(run_id).await;
                    return Err(e);
                }
            }
        };

        let (mut output, entities_detected, redactions_applied) =
            collect_output(run_id, &run_output);

        // Enforce retention policies from all submitted policies.
        self.apply_retention(input.actor_id, &input.policies, &input.graph, &mut output)
            .await;

        let status = run_output.run_status();
        self.inner
            .runs
            .finalize(run_id, status, entities_detected, redactions_applied)
            .await;

        Ok(output)
    }

    /// Enforce retention policies after a pipeline run.
    ///
    /// Iterates all retention policies across all submitted policies.
    /// For `ZeroRetention`, applies immediately:
    /// - `OriginalContent`: deletes imported content from the registry
    /// - `RedactedOutput`: deletes exported content from the registry
    /// - `AuditLogs`: clears audits from the output
    ///
    /// `Duration` and `Indefinite` retention are recorded as metadata
    /// but not enforced here (requires a background cleanup process).
    async fn apply_retention(
        &self,
        actor_id: Uuid,
        policies: &Policies,
        graph: &Graph,
        output: &mut EngineOutput,
    ) {
        let retention_policies = policies.all_retention();

        if retention_policies.is_empty() {
            return;
        }

        for rp in retention_policies {
            if !matches!(rp.retention, Retention::ZeroRetention) {
                continue;
            }
            match rp.scope {
                RetentionScope::OriginalContent => {
                    let content_ids: Vec<Uuid> = graph
                        .nodes
                        .iter()
                        .filter_map(|node| match &node.kind {
                            GraphNodeKind::ImportFile(cfg) => Some(cfg.content_ids.clone()),
                            _ => None,
                        })
                        .flatten()
                        .collect();
                    for id in content_ids {
                        if let Err(e) = self.inner.registry.unregister_content(actor_id, id).await {
                            tracing::warn!(
                                %id,
                                error = %e,
                                "failed to delete content for zero-retention",
                            );
                        }
                    }
                }
                RetentionScope::RedactedOutput => {
                    let content_ids: Vec<Uuid> = graph
                        .nodes
                        .iter()
                        .filter_map(|node| match &node.kind {
                            GraphNodeKind::ExportFile(cfg) => Some(cfg.content_ids.clone()),
                            _ => None,
                        })
                        .flatten()
                        .collect();
                    for id in content_ids {
                        if let Err(e) = self.inner.registry.unregister_content(actor_id, id).await {
                            tracing::warn!(
                                %id,
                                error = %e,
                                "failed to delete exported content for zero-retention",
                            );
                        }
                    }
                }
                RetentionScope::AuditLogs => {
                    output.audits.clear();
                }
                _ => {}
            }
        }
    }

    /// Compute a point-in-time [`AnalyticsSnapshot`] from all tracked runs.
    pub async fn snapshot(&self) -> AnalyticsSnapshot {
        self.inner.runs.snapshot().await
    }

    /// Get a full [`RunSnapshot`] including per-node status for a single run.
    ///
    /// Returns `None` if the run does not exist or belongs to a different actor.
    pub async fn get_run(&self, actor_id: Uuid, id: Uuid) -> Option<RunSnapshot> {
        self.inner.runs.get_run(actor_id, id).await
    }

    /// List runs matching the given filter, scoped to the actor.
    pub async fn list_runs(&self, actor_id: Uuid, filter: RunFilter) -> Vec<RunEntry> {
        self.inner.runs.list_runs(actor_id, &filter).await
    }

    /// Request cooperative cancellation of an in-progress run.
    ///
    /// Triggers the run's [`CancellationToken`](tokio_util::sync::CancellationToken),
    /// causing node tasks to abort at their next yield point.
    ///
    /// # Errors
    ///
    /// Returns `NotFound` if the run does not exist or belongs to a
    /// different actor, or `Validation` if the run has already finished.
    pub async fn cancel_run(&self, actor_id: Uuid, id: Uuid) -> Result<(), Error> {
        self.inner.runs.cancel_run(actor_id, id).await
    }

    /// Delete a single finished run from the in-memory store.
    ///
    /// # Errors
    ///
    /// Returns `NotFound` if the run does not exist or belongs to a
    /// different actor, or `Validation` if the run is still active.
    pub async fn delete_run(&self, actor_id: Uuid, id: Uuid) -> Result<(), Error> {
        self.inner.runs.delete_run(actor_id, id).await
    }

    /// Delete all finished runs for the actor. Active runs are preserved.
    ///
    /// Returns the number of removed entries.
    pub async fn delete_all_runs(&self, actor_id: Uuid) -> usize {
        self.inner.runs.delete_all_runs(actor_id).await
    }

    /// Store content in the registry and return the assigned identifier.
    ///
    /// # Errors
    ///
    /// Returns an error if the registry write fails.
    pub async fn upload_content(&self, actor_id: Uuid, content: Content) -> Result<Uuid, Error> {
        let handle = self
            .inner
            .registry
            .register_content(actor_id, content)
            .await?;
        Ok(handle.content_source().as_uuid())
    }

    /// Retrieve stored content data and metadata from the registry.
    ///
    /// # Errors
    ///
    /// Returns `NotFound` if the content does not exist.
    pub async fn download_content(
        &self,
        actor_id: Uuid,
        content_id: Uuid,
    ) -> Result<Content, Error> {
        let handle = self
            .inner
            .registry
            .read_content(actor_id, content_id)
            .await?;
        let data = handle.content_data().await?;
        let metadata = handle.metadata().await?;
        Ok(Content::with_metadata(data, metadata))
    }

    /// List all content identifiers stored for the given actor.
    pub async fn list_content(&self, actor_id: Uuid) -> Result<Vec<Uuid>, Error> {
        self.inner.registry.list_content(actor_id).await
    }

    /// List all content identifiers with metadata for the given actor.
    pub async fn list_content_with_metadata(
        &self,
        actor_id: Uuid,
    ) -> Result<Vec<(Uuid, ContentMetadata)>, Error> {
        self.inner
            .registry
            .list_content_with_metadata(actor_id)
            .await
    }

    /// Delete a single content entry from the registry.
    pub async fn delete_content(&self, actor_id: Uuid, content_id: Uuid) -> Result<(), Error> {
        self.inner
            .registry
            .unregister_content(actor_id, content_id)
            .await
    }

    /// Delete all content for the actor. Returns the number of entries removed.
    pub async fn delete_all_content(&self, actor_id: Uuid) -> Result<usize, Error> {
        self.inner.registry.unregister_all_content(actor_id).await
    }

    /// Store a context in the registry and return the assigned identifier.
    ///
    /// # Errors
    ///
    /// Returns an error if the registry write fails.
    pub async fn upload_context(&self, actor_id: Uuid, context: Context) -> Result<Uuid, Error> {
        let handle = self
            .inner
            .registry
            .register_context(actor_id, context)
            .await?;
        Ok(handle.source().as_uuid())
    }

    /// Retrieve a stored context from the registry.
    ///
    /// # Errors
    ///
    /// Returns `NotFound` if the context does not exist.
    pub async fn download_context(
        &self,
        actor_id: Uuid,
        context_id: Uuid,
    ) -> Result<Context, Error> {
        let handle = self
            .inner
            .registry
            .read_context(actor_id, context_id)
            .await?;
        handle.context().await
    }

    /// List all context identifiers stored for the given actor.
    pub async fn list_contexts(&self, actor_id: Uuid) -> Result<Vec<Uuid>, Error> {
        self.inner.registry.list_contexts(actor_id).await
    }

    /// Delete a single context entry from the registry.
    pub async fn delete_context(&self, actor_id: Uuid, context_id: Uuid) -> Result<(), Error> {
        self.inner
            .registry
            .unregister_context(actor_id, context_id)
            .await
    }

    /// Delete all contexts for the actor. Returns the number of entries removed.
    pub async fn delete_all_contexts(&self, actor_id: Uuid) -> Result<usize, Error> {
        self.inner.registry.unregister_all_contexts(actor_id).await
    }

    /// Returns the base data directory path backing the registry.
    pub fn data_dir(&self) -> &Path {
        self.inner.registry.base_dir()
    }
}

/// Aggregate entities, redaction records, and audits from all node
/// results into a single [`EngineOutput`].
///
/// Returns `(output, entities_detected, redactions_applied)` so the
/// caller can update the [`RunState`] counters during finalization.
fn collect_output(run_id: Uuid, run_output: &RunOutput) -> (EngineOutput, u64, u64) {
    let mut audits = Vec::new();
    let mut entities_detected = 0u64;
    let mut redactions_applied = 0u64;

    for nr in &run_output.node_results {
        for envelope in &nr.envelopes {
            entities_detected += envelope.audit.entities.len() as u64;
            redactions_applied += envelope
                .audit
                .entries
                .iter()
                .filter(|r| r.redaction.is_applied)
                .count() as u64;
            audits.push(envelope.audit.clone());
        }
    }

    let output = EngineOutput { run_id, audits };

    (output, entities_detected, redactions_applied)
}
