//! [`Engine`] — the main entry point for running redaction pipelines.
//!
//! The engine is a thin facade over the pipeline subsystem. It owns
//! shared infrastructure (registry, HTTP client, run state) and
//! delegates actual execution to [`Pipeline`] (one per run).
//!
//! [`Pipeline`]: super::run::Pipeline

use std::path::Path;
use std::sync::Arc;
use std::{fmt, mem};

use nvisy_core::Error;
use nvisy_ontology::provenance::AnyAudit;
use schemars::JsonSchema;
use serde::Serialize;
use tokio::sync::Mutex;
use tokio::task::JoinSet;
use uuid::Uuid;

use super::config::RuntimeConfig;
use super::run::Pipeline;
use super::runs::state::RunState;
use super::runs::{AnalyticsSnapshot, RunEntry, RunFilter, RunOutcome, RunSnapshot};
use crate::deduplication::DeduplicationParams;
use crate::detection::{Detection, Recognizers};
use crate::extraction::{Extraction, Extractors};
use crate::ingestion::encryption::SharedKeyProvider;
use crate::ingestion::registry::Registry;
use crate::ingestion::{ExportFile, ImportFile};
use crate::redaction::{Redaction, RedactionSection};
use crate::validation::Validation;

/// Input required to execute a redaction pipeline.
///
/// A flat, fixed-order plan. The order is hardwired
/// (extraction → detection → dedup → redaction → validation)
/// because downstream phases depend on upstream artifacts.
#[derive(Clone)]
pub struct EngineInput {
    /// Identity of the human or service account initiating the run.
    pub actor_id: Uuid,
    /// Previously uploaded policies to apply, in precedence order:
    /// index `0` is highest precedence.
    pub policies: Vec<Uuid>,
    /// When `true`, the pipeline evaluates detection and policy rules
    /// but skips validation and export.
    pub dry_run: bool,

    /// Content sources to ingest at the start of the run.
    pub imports: Vec<ImportFile>,
    /// Reference-data contexts to load into the cache before phases run.
    pub context_ids: Vec<Uuid>,

    /// Extraction settings per modality.
    pub extraction: Extraction,

    /// Detection settings (which recognizer kinds + per-call hints).
    pub detection: Detection,

    /// Deduplication settings applied to combined detection results.
    pub deduplication: DeduplicationParams,

    /// Redaction settings applied after policy evaluation.
    pub redaction: Redaction,

    /// Validation settings for the post-redaction leak check.
    pub validation: Validation,

    /// Sinks to export processed content to.
    pub exports: Vec<ExportFile>,
}

/// Complete result of a pipeline run.
#[derive(Debug, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct EngineOutput {
    /// Unique identifier for this run, generated by [`Engine::run`].
    pub run_id: Uuid,
    /// One audit per successfully processed document, modality-erased
    /// via [`AnyAudit`]. Carries entities, redaction entries, and
    /// content-source metadata. Failed documents do not appear here —
    /// look them up via [`Engine::get_run`] for per-document errors.
    pub audits: Vec<AnyAudit>,
}

/// Shared inner state for the engine, held behind an `Arc`.
///
/// All fields are immutable after construction except [`RunState`],
/// which uses internal `RwLock` synchronization.
pub(super) struct EngineInner {
    /// Configuration loaded once at engine startup. Sections like
    /// `[engine]`, `[extraction]`, `[detection]`, `[redaction]` are
    /// not overridable per-request — every run sees the same config.
    pub runtime_config: RuntimeConfig,
    /// Pre-built extractor registry, constructed once from
    /// `runtime_config.extraction` and shared across every run.
    pub extractors: Arc<Extractors>,
    /// Pre-built recognizer registry, constructed once from
    /// `runtime_config.detection` and shared across every run.
    pub recognizers: Arc<Recognizers>,
    /// Server-wide redaction defaults shared across every run.
    pub redaction_section: Arc<RedactionSection>,
    /// Content and context storage backend.
    pub registry: Registry,
    /// Encryption key provider for import/export decrypt/encrypt operations.
    pub key_provider: Option<SharedKeyProvider>,
    /// In-memory run lifecycle tracker (volatile: lost on restart).
    pub runs: RunState,
    /// Background pipeline tasks spawned by [`Engine::submit`].
    background_tasks: Mutex<JoinSet<()>>,
}

/// The redaction pipeline engine.
///
/// Thin facade over shared infrastructure. Actual pipeline execution
/// is delegated to `Pipeline` (one per run). All state lives in
/// `Arc<EngineInner>` and is shared across clones.
///
/// Builder methods ([`with_key_provider`]) require exclusive access
/// via `Arc::get_mut` and must be called before the engine is cloned.
///
/// [`with_key_provider`]: Engine::with_key_provider
#[derive(Clone)]
pub struct Engine {
    pub(super) inner: Arc<EngineInner>,
}

impl fmt::Debug for Engine {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Engine")
            .field("runtime_config", &self.inner.runtime_config)
            .finish()
    }
}

impl Engine {
    /// Open a new engine with the given configuration and data directory.
    ///
    /// Constructs the registry and run state. HTTP clients are now
    /// the responsibility of individual extraction ops, which build
    /// them per-call from `RuntimeConfig`. Async because future
    /// recognizer registrations may need to connect to externalized
    /// inference services on first use.
    ///
    /// # Errors
    ///
    /// Returns an error if the registry database cannot be opened.
    pub async fn open(data_dir: impl AsRef<Path>, config: RuntimeConfig) -> Result<Self, Error> {
        let registry = Registry::open(data_dir.as_ref())?;
        let extractors = Arc::new(
            config
                .extraction
                .as_ref()
                .map(Extractors::from_config)
                .transpose()?
                .unwrap_or_default(),
        );
        let recognizers = Arc::new(match config.detection.as_ref() {
            Some(section) => Recognizers::from_config(section).await?,
            None => Recognizers::default(),
        });
        let redaction_section = Arc::new(config.redaction.clone().unwrap_or_default());

        Ok(Self {
            inner: Arc::new(EngineInner {
                runtime_config: config,
                extractors,
                recognizers,
                redaction_section,
                registry,
                key_provider: None,
                runs: RunState::new(),
                background_tasks: Mutex::new(JoinSet::new()),
            }),
        })
    }

    /// Create a temporary engine backed by a [`tempfile`] directory.
    ///
    /// Uses default configuration. The directory is deleted when the
    /// returned [`TempDir`] is dropped: keep it alive for the duration
    /// of the test.
    ///
    /// # Panics
    ///
    /// Panics if the temp directory or registry cannot be created.
    ///
    /// [`tempfile`]: https://docs.rs/tempfile
    /// [`TempDir`]: tempfile::TempDir
    #[cfg(any(test, feature = "test-utils"))]
    pub async fn temp() -> (Self, tempfile::TempDir) {
        let dir = tempfile::tempdir().expect("failed to create temp directory");
        let engine = Self::open(dir.path(), RuntimeConfig::default())
            .await
            .expect("failed to open engine in temp directory");
        (engine, dir)
    }

    /// Set the key provider for encryption/decryption operations.
    ///
    /// # Panics
    ///
    /// Panics if the engine has already been cloned (Arc is shared).
    pub fn with_key_provider(mut self, provider: SharedKeyProvider) -> Self {
        Arc::get_mut(&mut self.inner)
            .expect("engine must not be shared during construction")
            .key_provider = Some(provider);
        self
    }

    /// Returns the base runtime configuration before per-request overrides.
    pub fn config(&self) -> &RuntimeConfig {
        &self.inner.runtime_config
    }

    /// Returns the content and context registry.
    pub fn registry(&self) -> &Registry {
        &self.inner.registry
    }

    /// Returns the base data directory path backing the registry.
    pub fn data_dir(&self) -> &Path {
        self.inner.registry.base_dir()
    }

    /// Create a new [`Pipeline`] bound to this engine's shared state.
    fn pipeline(&self) -> Pipeline {
        Pipeline::new(
            self.inner.registry.clone(),
            self.inner.key_provider.clone(),
            self.inner.runs.clone(),
            self.inner.runtime_config.clone(),
            Arc::clone(&self.inner.extractors),
            Arc::clone(&self.inner.recognizers),
            Arc::clone(&self.inner.redaction_section),
        )
    }

    /// Execute a full redaction pipeline synchronously (blocks until done).
    ///
    /// Acquires resources, runs every configured phase against each
    /// imported document, and collects results. Used directly in
    /// tests and the CLI.
    ///
    /// # Errors
    ///
    /// Returns an error if the run times out or all documents fail
    /// during execution.
    pub async fn run(&self, input: EngineInput) -> Result<EngineOutput, Error> {
        self.pipeline().run(input).await
    }

    /// Submit a pipeline run for background execution.
    ///
    /// Registers the run record synchronously, then spawns the
    /// actual execution on a background tokio task. Returns the run
    /// ID immediately.
    ///
    /// Results are persisted to the registry and can be retrieved via
    /// [`Engine::get_run`].
    pub async fn submit(&self, input: EngineInput) -> Result<Uuid, Error> {
        let pipeline = self.pipeline();
        let run_id = pipeline.id();
        let actor_id = input.actor_id;

        // Insert the initial Pending run record up front (cheap).
        pipeline.register_pending(&input).await;

        let registry = self.inner.registry.clone();
        let runs = self.inner.runs.clone();
        self.inner.background_tasks.lock().await.spawn(async move {
            match pipeline.execute(input).await {
                Ok(output) => {
                    if let Err(e) = registry.store_audits(actor_id, run_id, output.audits).await {
                        tracing::error!(%run_id, error = %e, "failed to persist run audits");
                        runs.fail(run_id, format!("failed to persist audits: {e}"))
                            .await;
                    }
                }
                Err(e) => {
                    tracing::error!(%run_id, error = %e, "background run failed");
                }
            }
        });
        Ok(run_id)
    }

    /// Get a full [`RunSnapshot`] including per-node status for a single run.
    ///
    /// For completed runs (`Succeeded`/`PartialFailure`), audit trails are
    /// loaded from the registry and included in the [`RunOutcome`].
    ///
    /// Returns `None` if the run does not exist or belongs to a different actor.
    pub async fn get_run(&self, actor_id: Uuid, id: Uuid) -> Option<RunSnapshot> {
        let mut snapshot = self.inner.runs.get_run(actor_id, id).await?;
        if let RunOutcome::Succeeded { audits, .. } | RunOutcome::PartialFailure { audits, .. } =
            &mut snapshot.outcome
            && let Ok(loaded) = self.inner.registry.load_audits(actor_id, id).await
        {
            *audits = loaded;
        }
        Some(snapshot)
    }

    /// Compute a point-in-time [`AnalyticsSnapshot`] from all tracked runs.
    pub async fn snapshot(&self) -> AnalyticsSnapshot {
        self.inner.runs.snapshot().await
    }

    /// List runs matching the given filter, scoped to the actor.
    pub async fn list_runs(&self, actor_id: Uuid, filter: RunFilter) -> Vec<RunEntry> {
        self.inner.runs.list_runs(actor_id, &filter).await
    }

    /// Request cooperative cancellation of an in-progress run.
    ///
    /// Triggers the run's [`CancellationToken`], causing node tasks to
    /// abort at their next yield point.
    ///
    /// # Errors
    ///
    /// Returns `NotFound` if the run does not exist or belongs to a
    /// different actor, or `Validation` if the run has already finished.
    ///
    /// [`CancellationToken`]: tokio_util::sync::CancellationToken
    pub async fn cancel_run(&self, actor_id: Uuid, id: Uuid) -> Result<(), Error> {
        self.inner.runs.cancel_run(actor_id, id).await
    }

    /// Delete a single finished run from the in-memory store.
    ///
    /// # Errors
    ///
    /// Returns `NotFound` if the run does not exist or belongs to a
    /// different actor, or `Validation` if the run is still active.
    pub async fn delete_run(&self, actor_id: Uuid, id: Uuid) -> Result<(), Error> {
        self.inner.runs.delete_run(actor_id, id).await?;
        let _ = self.inner.registry.unregister_audits(actor_id, id).await;
        Ok(())
    }

    /// Delete all finished runs for the actor. Active runs are preserved.
    ///
    /// Returns the number of removed entries.
    pub async fn delete_all_runs(&self, actor_id: Uuid) -> usize {
        let removed = self.inner.runs.delete_all_runs(actor_id).await;
        for id in &removed {
            let _ = self.inner.registry.unregister_audits(actor_id, *id).await;
        }
        removed.len()
    }

    /// Wait for all background pipeline tasks to complete.
    ///
    /// Call during graceful shutdown to ensure in-flight runs finish
    /// and persist their results before the process exits.
    pub async fn shutdown(&self) {
        let tasks = mem::take(&mut *self.inner.background_tasks.lock().await);
        tasks.join_all().await;
    }
}
