version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(deps-rs)"
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/packages/nvisy-ai"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "chore"
    commit-message:
      prefix: "chore(deps-py)"
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/packages/nvisy-exif"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "chore"
    commit-message:
      prefix: "chore(deps-py)"
    groups:
      rust-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "chore(actions)"
    groups:
      github-actions:
        patterns:
          - "*"
