# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "nvisy-pattern"
description = "Built-in regex patterns and dictionaries for PII/PHI detection"
keywords = ["nvisy", "pattern", "pii", "dictionary"]
categories = ["text-processing"]

version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# Internal crates
nvisy-core = { workspace = true, features = [] }

# (De)serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [] }
