# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "nvisy-http"
description = "Shared HTTP client with retry and tracing middleware for Nvisy"
keywords = ["nvisy", "http", "middleware"]
categories = ["web-programming::http-client"]
readme = "README.md"

version = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
# (De)serialization
serde = { workspace = true, features = [] }

# HTTP middleware
reqwest-middleware = { workspace = true, features = [] }
reqwest-retry = { workspace = true, features = [] }
reqwest-tracing = { workspace = true, features = [] }

# Observability
tracing = { workspace = true, features = [] }
