//! [`BoxedTextHandler`]: type-erased wrapper over all text handler types.

use nvisy_core::Error;
use nvisy_core::content::{ContentData, ContentSource};
use nvisy_core::media::DocumentType;

use super::{TextData, forward_edits, reindex_stream};
use crate::document::SpanStream;
use crate::handler::{Handler, TextHandler};

/// A type-erased text handler backed by a boxed trait object.
///
/// Normalises text span IDs to `usize` (positional index) so that
/// heterogeneous text handlers can be used interchangeably.
pub struct BoxedTextHandler(Box<dyn DynTextHandler>);

impl BoxedTextHandler {
    /// Wrap any concrete text handler into a boxed, type-erased wrapper.
    fn new<H: DynTextHandler>(handler: H) -> Self {
        Self(Box::new(handler))
    }
}

impl std::fmt::Debug for BoxedTextHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("BoxedTextHandler")
            .field(&self.0.document_type())
            .finish()
    }
}

impl Handler for BoxedTextHandler {
    fn document_type(&self) -> DocumentType {
        Handler::document_type(self.0.as_ref())
    }

    fn source(&self) -> ContentSource {
        Handler::source(self.0.as_ref())
    }

    fn encode(&self) -> Result<ContentData, Error> {
        Handler::encode(self.0.as_ref())
    }
}

#[async_trait::async_trait]
impl TextHandler for BoxedTextHandler {
    type TextId = usize;

    async fn text_spans(&self) -> SpanStream<'_, usize, TextData> {
        self.0.text_spans_reindexed().await
    }

    async fn edit_text(&mut self, edits: SpanStream<'_, usize, TextData>) -> Result<(), Error> {
        self.0.edit_text_reindexed(edits).await
    }
}

/// Object-safe private supertrait that bridges [`Handler`] and
/// [`TextHandler`] for dynamic dispatch.
///
/// Text handlers have heterogeneous `TextId` types (e.g. `TxtSpan`,
/// `CsvSpan`, `JsonPath`). This trait normalises them to `usize` via
/// [`reindex_stream`] and [`forward_edits`], allowing
/// [`BoxedTextHandler`] to present a uniform
/// `TextHandler<TextId = usize>` interface.
///
/// Concrete implementations are generated by [`impl_dyn_text!`].
#[async_trait::async_trait]
pub(crate) trait DynTextHandler: Handler {
    /// Return text spans with IDs re-mapped to sequential `usize` indices.
    async fn text_spans_reindexed(&self) -> SpanStream<'_, usize, TextData>;

    /// Accept `usize`-keyed edits and forward them back using the
    /// handler's native [`TextId`](crate::handler::TextHandler::TextId).
    async fn edit_text_reindexed(
        &mut self,
        edits: SpanStream<'_, usize, TextData>,
    ) -> Result<(), Error>;
}

macro_rules! impl_dyn_text {
    ($ty:ty) => {
        #[async_trait::async_trait]
        impl DynTextHandler for $ty {
            async fn text_spans_reindexed(&self) -> SpanStream<'_, usize, TextData> {
                reindex_stream(self).await
            }

            async fn edit_text_reindexed(
                &mut self,
                edits: SpanStream<'_, usize, TextData>,
            ) -> Result<(), Error> {
                use futures::StreamExt;
                let edits: Vec<_> = edits.collect().await;
                forward_edits(self, edits).await
            }
        }

        impl From<$ty> for BoxedTextHandler {
            fn from(h: $ty) -> Self {
                Self::new(h)
            }
        }
    };
}

use super::{CsvHandler, JsonHandler, TxtHandler};
impl_dyn_text!(TxtHandler);
impl_dyn_text!(CsvHandler);
impl_dyn_text!(JsonHandler);

#[cfg(feature = "html")]
use super::HtmlHandler;
#[cfg(feature = "html")]
impl_dyn_text!(HtmlHandler);

#[cfg(feature = "xlsx")]
use super::XlsxHandler;
#[cfg(feature = "xlsx")]
impl_dyn_text!(XlsxHandler);

#[cfg(test)]
mod tests {
    use futures::StreamExt;
    use nvisy_core::media::TextFormat;

    use super::*;
    use crate::handler::TxtHandler;

    #[test]
    fn txt_variant_document_type() {
        let h = BoxedTextHandler::from(TxtHandler::new(vec!["hello".into()], false));
        assert_eq!(
            h.document_type(),
            DocumentType::Text(TextFormat::Txt),
        );
    }

    #[tokio::test]
    async fn view_spans_returns_text() {
        let h = BoxedTextHandler::from(TxtHandler::new(
            vec!["line1".into(), "line2".into()],
            false,
        ));
        let spans: Vec<_> = h.text_spans().await.collect().await;
        assert_eq!(spans.len(), 2);
        assert_eq!(spans[0].id, 0);
        assert_eq!(spans[1].id, 1);
    }

    #[test]
    fn from_conversions() {
        let txt: BoxedTextHandler = TxtHandler::new(vec![], false).into();
        assert!(matches!(txt.document_type(), DocumentType::Text(TextFormat::Txt)));
    }

    #[test]
    fn encode_delegates() {
        let h = BoxedTextHandler::from(TxtHandler::new(vec!["hello".into()], false));
        assert!(h.encode().is_ok());
    }
}
