//! [`BoxedRichHandler`]: type-erased wrapper over all rich-document handler types.

use nvisy_core::Error;
use nvisy_core::media::DocumentType;
use nvisy_core::content::ContentData;
use nvisy_core::content::ContentSource;

#[cfg(feature = "pdf")]
use super::RichTextHandler;
use crate::document::SpanStream;
use crate::handler::text::{TextData, forward_edits, reindex_stream};
use crate::handler::{Handler, TextHandler};

/// A type-erased rich-document handler backed by a boxed trait object.
///
/// Normalises text span IDs to `usize` (positional index) so that
/// heterogeneous rich handlers can be used interchangeably.
pub struct BoxedRichHandler(Box<dyn DynRichHandler>);

impl BoxedRichHandler {
    fn new<H: DynRichHandler>(handler: H) -> Self {
        Self(Box::new(handler))
    }
}

impl std::fmt::Debug for BoxedRichHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("BoxedRichHandler")
            .field(&self.0.document_type())
            .finish()
    }
}

#[cfg(feature = "pdf")]
impl From<RichTextHandler> for BoxedRichHandler {
    fn from(h: RichTextHandler) -> Self {
        Self::new(h)
    }
}

impl Handler for BoxedRichHandler {
    fn document_type(&self) -> DocumentType {
        Handler::document_type(self.0.as_ref())
    }

    fn source(&self) -> ContentSource {
        Handler::source(self.0.as_ref())
    }

    fn encode(&self) -> Result<ContentData, Error> {
        Handler::encode(self.0.as_ref())
    }
}

#[async_trait::async_trait]
impl TextHandler for BoxedRichHandler {
    type TextId = usize;

    async fn text_spans(&self) -> SpanStream<'_, usize, TextData> {
        self.0.text_spans_reindexed().await
    }

    async fn edit_text(&mut self, edits: SpanStream<'_, usize, TextData>) -> Result<(), Error> {
        self.0.edit_text_reindexed(edits).await
    }
}

/// Object-safe private supertrait that bridges [`Handler`] and
/// [`TextHandler`] for dynamic dispatch.
///
/// Rich-document handlers have heterogeneous `TextId` types (e.g.
/// [`RichTextSpan`](super::RichTextSpan) for PDF). This trait
/// normalises them to `usize` via [`reindex_stream`] and
/// [`forward_edits`], allowing [`BoxedRichHandler`] to present a
/// uniform `TextHandler<TextId = usize>` interface.
///
/// Concrete implementations are generated by [`impl_dyn_rich!`].
#[async_trait::async_trait]
trait DynRichHandler: Handler {
    /// Return text spans with IDs re-mapped to sequential `usize` indices.
    async fn text_spans_reindexed(&self) -> SpanStream<'_, usize, TextData>;

    /// Accept `usize`-keyed edits and forward them back using the
    /// handler's native [`TextId`](crate::handler::TextHandler::TextId).
    async fn edit_text_reindexed(
        &mut self,
        edits: SpanStream<'_, usize, TextData>,
    ) -> Result<(), Error>;
}

macro_rules! impl_dyn_rich {
    ($ty:ty) => {
        #[async_trait::async_trait]
        impl DynRichHandler for $ty {
            async fn text_spans_reindexed(&self) -> SpanStream<'_, usize, TextData> {
                reindex_stream(self).await
            }

            async fn edit_text_reindexed(
                &mut self,
                edits: SpanStream<'_, usize, TextData>,
            ) -> Result<(), Error> {
                use futures::StreamExt;
                let edits: Vec<_> = edits.collect().await;
                forward_edits(self, edits).await
            }
        }
    };
}

#[cfg(feature = "pdf")]
impl_dyn_rich!(RichTextHandler);
