//! [`BoxedImageHandler`]: type-erased wrapper over all image handler types.

use nvisy_core::Error;
use nvisy_core::fs::DocumentType;
use nvisy_core::io::ContentData;
use nvisy_core::path::ContentSource;

use super::{ImageData, ImageSpanId, JpegHandler, PngHandler};
use crate::document::SpanStream;
use crate::handler::{Handler, ImageHandler};

/// A type-erased image handler backed by a boxed trait object.
///
/// All image handlers share `ImageId = ImageSpanId`, so a single
/// boxed trait object can unify them without per-variant boilerplate.
pub struct BoxedImageHandler(Box<dyn DynImageHandler>);

impl BoxedImageHandler {
    /// Wrap any concrete image handler into a type-erased box.
    fn new<H: DynImageHandler>(handler: H) -> Self {
        Self(Box::new(handler))
    }
}

impl std::fmt::Debug for BoxedImageHandler {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("BoxedImageHandler")
            .field(&self.0.document_type())
            .finish()
    }
}

impl From<PngHandler> for BoxedImageHandler {
    fn from(h: PngHandler) -> Self {
        Self::new(h)
    }
}

impl From<JpegHandler> for BoxedImageHandler {
    fn from(h: JpegHandler) -> Self {
        Self::new(h)
    }
}

impl Handler for BoxedImageHandler {
    fn document_type(&self) -> DocumentType {
        Handler::document_type(self.0.as_ref())
    }

    fn source(&self) -> ContentSource {
        Handler::source(self.0.as_ref())
    }

    fn encode(&self) -> Result<ContentData, Error> {
        Handler::encode(self.0.as_ref())
    }
}

#[async_trait::async_trait]
impl ImageHandler for BoxedImageHandler {
    type ImageId = ImageSpanId;

    async fn image_spans(&self) -> SpanStream<'_, ImageSpanId, ImageData> {
        self.0.image_spans().await
    }

    async fn edit_images(
        &mut self,
        edits: SpanStream<'_, ImageSpanId, ImageData>,
    ) -> Result<(), Error> {
        self.0.edit_images(edits).await
    }
}

/// Object-safe private supertrait that bridges [`Handler`] and
/// [`ImageHandler`] for dynamic dispatch.
///
/// [`ImageHandler`] has an associated type (`ImageId`), which prevents
/// it from being directly object-safe. This trait fixes `ImageId` to
/// [`ImageSpanId`] so that standalone image handlers (PNG, JPEG) can
/// be boxed behind a single `dyn DynImageHandler`.
///
/// Concrete implementations are generated by [`impl_dyn_image!`].
#[async_trait::async_trait]
trait DynImageHandler: Handler {
    /// Forward to [`ImageHandler::image_spans`] with `ImageId = ImageSpanId`.
    async fn image_spans(&self) -> SpanStream<'_, ImageSpanId, ImageData>;

    /// Forward to [`ImageHandler::edit_images`] with `ImageId = ImageSpanId`.
    async fn edit_images(
        &mut self,
        edits: SpanStream<'_, ImageSpanId, ImageData>,
    ) -> Result<(), Error>;
}

macro_rules! impl_dyn_image {
    ($ty:ty) => {
        #[async_trait::async_trait]
        impl DynImageHandler for $ty {
            async fn image_spans(&self) -> SpanStream<'_, ImageSpanId, ImageData> {
                ImageHandler::image_spans(self).await
            }

            async fn edit_images(
                &mut self,
                edits: SpanStream<'_, ImageSpanId, ImageData>,
            ) -> Result<(), Error> {
                ImageHandler::edit_images(self, edits).await
            }
        }
    };
}

impl_dyn_image!(PngHandler);
impl_dyn_image!(JpegHandler);

#[cfg(test)]
mod tests {
    use futures::StreamExt;

    use super::*;

    fn make_png() -> PngHandler {
        let img = image::DynamicImage::new_rgb8(1, 1);
        PngHandler::new(img)
    }

    fn make_jpeg() -> JpegHandler {
        let img = image::DynamicImage::new_rgb8(1, 1);
        JpegHandler::new(img)
    }

    #[test]
    fn png_variant_document_type() {
        let h = BoxedImageHandler::from(make_png());
        assert_eq!(
            h.document_type(),
            DocumentType::Image(nvisy_core::fs::ImageFormat::Png),
        );
    }

    #[test]
    fn jpeg_variant_document_type() {
        let h = BoxedImageHandler::from(make_jpeg());
        assert_eq!(
            h.document_type(),
            DocumentType::Image(nvisy_core::fs::ImageFormat::Jpeg),
        );
    }

    #[tokio::test]
    async fn view_spans_returns_image() {
        let h = BoxedImageHandler::from(make_png());
        let spans: Vec<_> = h.image_spans().await.collect().await;
        assert_eq!(spans.len(), 1);
    }

    #[test]
    fn from_conversions() {
        let png = BoxedImageHandler::from(make_png());
        assert_eq!(
            png.document_type(),
            DocumentType::Image(nvisy_core::fs::ImageFormat::Png),
        );
        let jpeg = BoxedImageHandler::from(make_jpeg());
        assert_eq!(
            jpeg.document_type(),
            DocumentType::Image(nvisy_core::fs::ImageFormat::Jpeg),
        );
    }

    #[test]
    fn encode_delegates() {
        let h = BoxedImageHandler::from(make_png());
        assert!(h.encode().is_ok());
    }
}
